### ISSUE TITLE
Error: Cannot find module 'jscrambler-webpack-plugin'

### ISSUE THREAD

**Issue by ConjecturDev** [jscrambler/jscrambler-webpack-plugin#1]
Npm is unable to recognize the module because the lib/index.js file is not included in the package.

It looks like your prepublish command is not running before it gets published. We had to manually run `npm run build` inside `node_modules/jscrambler-webpack-plugin` to get the package to work.

**Comment by magalhas** [comment]
Hi. It should be fixed on the newest release (1.0.2). Sorry for the inconvenience, please let me know if it's working.
